### PR TITLE
Fix .d.ts

### PR DESCRIPTION
**Pull request by tripodsgames**
Module declaration did not work because index.d.ts is not a rootType, so I created a declaration file for each mode.

### CODE REVIEW

**Comment by lukeed** [comment]
Hmm may I ask for your settings / a repro? What's published currently is working on my end

**Comment by tripodsgames** [comment]
Sure, I use typescript in a very strict mode

tsconfig.json:
```
{
    "compilerOptions": {
        "declaration": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "lib": [
            "ES2018"
        ],
        "module": "commonjs",
        "newLine": "LF",
        "esModuleInterop": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitThis": true,
        "noUnusedParameters": true,
        "noUnusedLocals": true,
        "outDir": "dist",
        "sourceMap": true,
        "strictNullChecks": true,
        "target": "ES2018",
        "typeRoots": [
            "typings",
            "node_modules/@types"
        ]
    },
    "include": [
        "src/**/*.ts"
    ],
    "exclude": [
        "typings"
    ]
}
```

**Comment by tripodsgames** [comment]
image
At compile time I'm getting this error.

**Comment by lukeed** [comment]
Thanks! I'll be back to my desk in a little bit and run through then.
I'm confused though since we're already doing exactly what the error message says to do

**Comment by tripodsgames** [comment]
> Thanks! I'll be back to my desk in a little bit and run through then.
> I'm confused though since we're already doing exactly what the error message says to do

Me too, sometimes typescript is weird.

image
Inside the typings folder(typeRoots) it works...

**Comment by lukeed** [comment]
Oh. I just noticed your typeRoots config.
You are literally _telling_ TS to ignore any other locations. Please see [docs](https://www.typescriptlang.org/tsconfig#typeRoots) for this.

I recommend you move your `typings` directory, which I assume is your project's custom types, into `src/@types` or `@types` (root). You want to make use of the native resolution steps. Setting _any_ value immediately disables normal lookup patterns

**Comment by tripodsgames** [comment]
> Oh. I just noticed your typeRoots config.
> You are literally _telling_ TS to ignore any other locations. Please see [docs](https://www.typescriptlang.org/tsconfig#typeRoots) for this.
> 
> I recommend you move your `typings` directory, which I assume is your project's custom types, into `src/@types` or `@types` (root). You want to make use of the native resolution steps. Setting _any_ value immediately disables normal lookup patterns

I'll try.

**Comment by lukeed** [comment]
I've run into this before -- was definitely annoying and unsurprising 😅 
Don't forget to remove that config once you've renamed your directory.

**Comment by tripodsgames** [comment]
> I've run into this before -- was definitely annoying and unexpected sweat_smile
> Don't forget to remove that config once you've renamed your directory.

:(
I tested other configurations and they also failed, could you send your tsconfig for me to test?

**Comment by lukeed** [comment]
Shit – you're right! I've got some serious double-checking to do in my projects~

I want to make some adjustments to your PR(s) but let's get this in.

**Comment by tripodsgames** [comment]
> Shit – you're right! I've got some serious double-checking to do in my projects~
> 
> I want to make some adjustments to your PR(s) but let's get this in.

If you want, i can create a project in typescript(strict) for testing your libraries.

**Comment by lukeed** [comment]
Thanks :) I think my public stuff should be pretty easy to find & fix. I really meant my private things that followed the same pattern. Definitely feel free to open an issue on anything you see that I forgot though!

**Comment by lukeed** [comment]
These PRs inspired me to add type-definition management inside [`bundt`](https://github.com/lukeed/bundt). 
Now, when a "mode" source file is built, `bundt` will copy its related `*.d.ts` file (if exists) into the proper directory.

I probably won't make use of it inside dequal/klona, since they just need the `xargs | copy` script, but everything else will definitely need it. 👍

**Pull request merged**
